name: Build yuedu_source file
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install python package
        run: |
          pip install --upgrade pip wheel
          pip install demjson
          pip install requests
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: makefile
        run: |
          python makefile.py
          python clear.py
          mkdir -p ./publish
          mv ./clear_yuedu_source.json ./publish/yuedu_source.json
          mv ./yuedu_source.json ./publish/no_clear_yuedu_source.json

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
        run: |
          files=$(ls ./publish)
          for ASSET in ${files}; do
            FILEPATH="./publish/${ASSET}"
            FILETYPE=$(file -b --mime-type "${FILEPATH}")
            CONTENT_TYPE_HEADER="Content-Type: ${FILETYPE}"
            AUTH_HEADER="Authorization: token ${{ env.GITHUB_TOKEN }}"
            URL="https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.release_id }}/assets?name=${ASSET}"
            curl -sSL -X POST -H "${AUTH_HEADER}" -H "${CONTENT_TYPE_HEADER}" --data-binary @${FILEPATH} ${URL}
          done
